Neos:
  Fusion:
    defaultContext:
      'Wysiwyg.ABTesting.Decisions': 'Wysiwyg\ABTesting\Eel\DecisionHelper'
      'Wysiwyg.ABTesting.Features': 'Wysiwyg\ABTesting\Eel\FeatureHelper'
  Neos:
    userInterface:
      translation:
        autoInclude:
          Wysiwyg.ABTesting:
            - Main

    fusion:
      autoInclude:
        'Wysiwyg.ABTesting': TRUE

    modules:
      AbTesting:
        label: 'A/B Testing'
        description: 'A/B Testing Dashboard'
        controller: Wysiwyg\ABTesting\Controller\Module\AbTestingController
        icon: icon-briefcase
        submodules:
          features:
            icon: icon-cog
            label: 'Features'
            description: 'Configurations of A/B Testing Features'
            controller: Wysiwyg\ABTesting\Controller\Module\AbTesting\FeatureModuleController
            privilegeTarget: Wysiwyg.ABTesting:Module.AbTesting.Feature
            widgetTemplatePathAndFileName: 'resource://Neos.Neos/Private/Templates/Module/Widget.html'
            actions:
              newFeature:
                label: 'Create Feature'
                title: 'Create Feature'
              listFeatures:
                label: 'Feature List'
                title: 'Feature List'
  Flow:
    http:
      chain:
        postprocess:
          chain:
            abTesting:
              component: Wysiwyg\ABTesting\Domain\Http\AbTestingCookieComponent

Wysiwyg:
  ABTesting:
    cookie:
      name: 'WYSIWYG_AB_TESTING'
      lifetime: '+2 years' # will be used for strtotime
